### ISSUE TITLE
Failure to cite libraries used in paper

### ISSUE THREAD

**Issue by stefanv** [AllenInstitute/aics-segmentation#1]
In the [segmenter BioArxiv paper](https://www.biorxiv.org/content/10.1101/491035v1) there is no citation of the underlying libraries, such as NumPy, SciPy, and scikit-image.  Would it be possible to rectify the situation by releasing a new version of the paper?

The authors of those libraries depend on citations to 1. know when their libraries are used and 2. request funding because those libraries play an important role in the ecosystem.  Thank you for understanding!

**Comment by Kimcmetzler** [comment]
Hi @stefanv 

We apologize for the oversight, and definitely will include all the citations for the libraries used in our code. We will identify all the libraries used and update the BioRxiv paper as soon as possible. Thank you! 

Kim Metzler
Scientific Program Manager @ the Allen Institute for Cell Science

**Comment by stefanv** [comment]
No problem, thank you for the friendly response!  I found this issue because I'm citing your paper in an upcoming publication :)

**Comment by jxchen01** [comment]
@stefanv We updated our bioRxiv paper recently to include a lot of method updates as well as the reference updates. Thanks again for your kind suggestion.
