### ISSUE TITLE
batch_processing.py does not recognize tiff files in some cases

### ISSUE THREAD

**Issue by gewitterblitz** [AllenInstitute/aics-segmentation#2]
Hi,

I have been trying to segment some of my data using batch_processing.py in classic code. I have been doing segmentation over two sets of data which have exactly similar file structure (as in data.shape, data file extension being tiff). However, one set of files run perfectly fine but the run_toolkit.sh script shows the following error for the other set of files:

```AICSImage module does not support this image file type: 	CellImage can only accept OME-TIFF, TIFF, and CZI file formats!```

Surprisingly, when I read in the same data file in an ipython console, I can very well read the data and segment it.

Not sure what's going wrong here. Could someone please throw some light on this?

NOTE: I don't think it should matter but I would also mention that I am trying to run batch_processing.py for both the datasets simultaneously using their respective run_toolkit.sh bash scripts.

Here's my run_toolkit.sh bash script:

```#!/usr/bin/env bash

WFNAME=supercell
INPUTCH=2
OUTPUTDIR="/Users/sharm261/Desktop/stack_images_zdr/segmented_stacks/"
INPUTFILE_TYPE='.tif'

# script for processing a whole folder
INPUTDIR="/Users/sharm261/Desktop/original_img_stack/"

python batch_processing.py \
        --d \
        --workflow_name $WFNAME \
        --struct_ch $INPUTCH \
        --output_dir $OUTPUTDIR \
        per_dir \
        --input_dir $INPUTDIR \
        --data_type $INPUTFILE_TYPE```

**Comment by jxchen01** [comment]
Are you running within a conda environment as the installation guide suggested? If so, can you copy and paste the console output after running `pip show aicssegmentation` and `pip show `pip show aicsimageio`?

**Comment by milindsharma1** [comment]
Yes, running this in a conda environment. Here's the output for ```pip show aicssegmentation```
```
Name: aicssegmentation
Version: 0.1.16.dev4
Summary: Scripts for structure segmentation.
Home-page: UNKNOWN
Author: AICS
Author-email: jianxuc@alleninstitute.org
License: Allen Institute Software License
Location: /Users/sharm261/Documents/aics-segmentation
Requires: numpy, scipy, scikit-image, pandas, aicsimageio, aicsimageprocessing, numba, itk
Required-by:
```
and ```pip show aicsimageio```

```
Name: aicsimageio
Version: 0.6.4
Summary: A generalized scientific image processing module from the Allen Institute for Cell Science.
Home-page: UNKNOWN
Author: AICS
Author-email: !AICS_SW@alleninstitute.org
License: Allen Institute Software License
Location: /anaconda3/envs/segmentation/lib/python3.6/site-packages
Requires: matplotlib, scipy, numpy, scikit-image, Pillow, imageio, tifffile
Required-by: aicssegmentation
```

**Comment by jxchen01** [comment]
The packages look correct to me. There are a couple to easy/quick things to try.

(1) If you simply add `print(filenames)` in https://github.com/AllenInstitute/aics-segmentation/blob/master/aicssegmentation/bin/batch_processing.py#L216

The detected files should be printed out to your screen console. Then, you can make sure they are exactly what you are trying to run on.

(2) If the filenames shown in the test above are different from what you are expecting, you can try insert `print(os.listdir(args.input_dir))` as you did above. This is kind of making sure the program is getting the correct directory.
