### ISSUE TITLE
batch_processing fails to generate output when I lock the computer screen

### ISSUE THREAD

**Issue by gewitterblitz** [AllenInstitute/aics-segmentation#3]
Hi,

I have been using batch_processing.py (run with run_toolkit.sh bash script) to perform segmentation for my data. Once I execute the bash script, I start getting the output as per expectation.

However, when I lock the screen so as to wait for the segmentation overnight, I see that the processing had stalled at the very moment where I had left before locking the screen. I am NOT letting the computer to go to sleep (just locking screen).

Anyone has any clues why this might be happening?

Note: I am using an iMac which has macOD High Sierra version 10.13.6

**Comment by jxchen01** [comment]
I am not a heavy MacOS user. I only use it for testing the segmenter and some basic demo. I will try my best to help.

The first thing came into my mind is the setting on MacOS "System Preference --> Energy Saver --> " , where you can change when to put computer/hard disk to sleep. You can try to get rid of these and see if it helps.

Thanks,
Jianxu

**Comment by milindsharma1** [comment]
I had the computer on 'no sleep' mode as you suggested. However, the batch processing pauses while the screen is locked.

It resumes as soon as I turn on the screen.

**Comment by jxchen01** [comment]
If so, I would suggest to try "GNU screen", which is a standard tool on Linux to leave a command running in the background safely. GNU screen is also available on MacOS. See this: 
 https://www.nyayapati.com/srao/2013/02/gnu-screen-on-mac-osx/
